### ISSUE TITLE
Fullbright + NoFog suggestion

### ISSUE THREAD

**Issue by SSean08** [Furzide/RenderDragonFogRemover#2]
Can you combine Fullbright + Fog remover?

**Comment by SSean08** [comment]
Found your build environment repo and nofog branch in the Fullbright repo. I decided to compile it and run it but all blocks were invisible.

See screenshots

What I've done:

1. Deleted everything in the build environments materials directory
2. Copied all the files in the Fullbright nofog branch and put them in the build environment's _materials_ folder.
3. Run **build.bat -t 4**
4. Build was successful.
5. Copied everything to my minecraft
6. Didn't work

I'm trying to test now if I did something wrong by compiling fullbright myself.


![image](https://github.com/user-attachments/assets/636a3b4e-d1da-43d6-a0a7-52009d1deadd)

**Comment by SSean08** [comment]
Compiling Fullbright from source with the build environment didn't work, it's the same as above. I think I'm doing something wrong or I might have missed something. It would have been convenient if I'm able to understand batch script lang but I don't.

**Comment by Furzide** [comment]
you are probably using wrong version of mbt or something or are missing certain includes

**Comment by SSean08** [comment]
What can I do though? Do you have any pointers on where I can start, guides, etc? Or you might as well send your own build environment, it might help I think if the problem is some _includes_ or a _wrong version of mbt_.

**Comment by SSean08** [comment]
I've compiled it successfully, nofog is fully working.
What i've done is I looked at some forks of the build environment and found one with minecraft 1.21 as the base, used it and it worked!
